openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/a.slobodyanyuk/petstore/1.0.0'
paths:
  /account/lead:
    post:
      tags:
        - account
        - lead
        - customer
      summary: register a new Lead
      operationId: __invoke
      responses:
        '201':
          $ref: '#/components/responses/CreatedLead'
        '422':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      description: Allow to register a new Lead in system
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/NewLead'
components:
  schemas:
    Lead:
      xml:
        name: Pet
      x-examples:
        An Lead:
          $ref: '#/components/examples/newLead'
      x-internal: false
      title: ''
      description: ''
      anyOf:
        - properties:
            id:
              type: integer
              nullable: true
            publicId:
              type: string
              nullable: true
            name:
              type: string
              example: doggie
            email:
              type: string
            phone:
              xml:
                name: photoUrl
                wrapped: true
              type: integer
            '':
              type: object
              properties:
                id:
                  type: string
                '':
                  type: string
          required:
            - name
            - email
            - phone
      type: object
  requestBodies:
    NewLead:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              phone:
                type: integer
              some:
                type: string
        application/xml:
          schema:
            type: object
            properties: {}
      description: first data for new lead
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  responses:
    ErrorResponse:
      description: Basic Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: integer
    CreatedLead:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: integer
              public_id:
                type: string
              name:
                type: string
              email:
                type: string
              phone:
                type: integer
  examples:
    newLead:
      value:
        description: Request for a new Lead
        type: object
        properties:
          name: John Doe
          email: john.doe@mail.com
          phone: 380971234567
        required:
          - name
          - email
          - phone
